#!/usr/bin/perl
use strict;
use warnings;

while (<>) {
	
	my $input = $_;
	if ( $input =~ /
				\b and \b |
				\b that \b |
				\b it \b | 
				\b be \b |
				\b who's \b | 
				\b fuck \b | 
				\b with \b |
				's \b | 
				\b are \b |
				\b was  \b | 
				\b have \b | 
				\b this \b | 
				\b which \b | 
				\b you \b | 
				\b but \b | 
				\b wrote \b | 
				\b from \b | 
				\b has \b | 
				\b there \b |
				\b can \b | 
				\b will \b | 
				\b all \b | 
				\b they \b | 
				\b been \b | 
				\b may \b | 
				\b who \b | 
				\b their \b | 
				\b work \b | 
				\b about \b | 
				\b had \b | 
				\b what \b | 
				\b some \b | 
				\b other \b | 
				\b also \b | 
				\b only \b | 
				\b when \b | 
				\b time \b | 
				\b were \b | 
				\b your \b | 
				\b than \b | 
				\b two \b | 
				\b would \b | 
				\b like \b | 
				\b out \b | 
				\b such \b | 
				\b them \b | 
				\b into \b | 
				\b well \b | 
				\b first \b | 
				\b these \b | 
				\b any \b | 
				\b people \b | 
				\b said \b | 
				\b then \b | 
				\b those \b | 
				\b life \b | 
				\b where \b | 
				\b even \b | 
				\b glass \b | 
				\b could \b | 
				\b being \b | 
				\b how \b | 
				\b very \b | 
				\b though \b | 
				\b many \b | 
				\b way \b | 
				\b make \b | 
				\b much \b | 
				\b between \b | 
				\b after \b | 
				\b most \b | 
				\b both \b | 
				\b still \b | 
				\b should \b | 
				\b made \b | 
				\b own \b | 
				\b course \b | 
				\b always \b | 
				\b say \b | 
				\b long \b | 
				\b under \b | 
				\b take \b | 
				\b good \b | 
				\b perhaps \b | 
				\b think \b | 
				\b does \b | 
				\b last \b | 
				\b because \b | 
				\b get \b | 
				\b through \b | 
				\b here \b | 
				\b never \b | 
				\b old \b | 
				\b since \b | 
				\b less \b | 
				\b however \b | 
				\b right \b | 
				\b another \b | 
				\b often \b | 
				\b must \b | 
				\b something \b | 
				\b itself \b | 
				\b might \b | 
				\b while \b | 
				\b against \b | 
				\b can't \b | 
				\b did \b | 
				\b didn't \b | 
				\b don't \b | 
				\b going \b | 
				\b got \b | 
				\b he's \b | 
				\v she's \b |
				\b I'll \b | 
				\b I'm \b | 
				\b it's \b | 
				\b know \b | 
				\b look \b | 
				\b mean \b | 
				\b really \b | 
				\b see \b | 
				\b tell \b | 
				\b that's \b | 
				\b up \b | 
				\b want \b | 
				\b why \b | 
				\b you're \b 	
	\b hella \b |
	\b iam \b |
	\b im \b |
	\b iono \b |
	\b lames \b |
	\b koo \b |
	\b omw \b |
	\b cya \b |
	\b c u \b | 
	\b y'all \b |
	\b'em\b |
	\b smh \b |
	\b wassup \b |
	\b suttin \b |
	\b wyd \b |
	\b diy \b |
	\b 'bro \b |
	\b readin \b |
	\b wots \b |
	\b wats \b |
	\b wot \b |
	\b asap \b |
	\b afk \b |
	\b tho \b |
	\b abt \b |
	\b asa \b |
	\b i ll \b |
	\b b4 \b |
	\b cuzin \b |
	\b tmro \b |
	\b theres \b |
	\b aswell\ b |
	\b doin \b |
	\b goin \b |
	\b hav \b |
	\b havin \b |
	\b thinkin \b |
	\b startin \b |
	\b sayin \b | 
	\b bout \b |
	\b tryna \b |
	\b w\/out \b |
	\b w\/.* \b |
	\b outta \b |
	\b gotta \b |
	\b ppl\b |
	\b lmao\b |
	\b ffs \b |
	\b 2moro \b |
	\b rofl \b |
	\b wtf \b |
	\b fuckin \b |
	\b god \b |
	\b omg \b |
	\b omfg \b |
	\b bruva \b |
	\b brova \b |
	\b u r \b |
	\b urs \b |
	\b dat \b	/ix)
	{print $input;}

	 }
